FROM php:8.1-apache

# Copy the PHP files into the container
COPY index.php /var/www/html/

# Install the MySQL extension for PHP
RUN docker-php-ext-install mysqli pdo_mysql

# Set the permissions for www-data
RUN chown -R www-data:www-data /var/www/html && chmod -R o-rwx /var/www/html

# Enable use of .htaccess files
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

RUN service apache2 restart

CMD ["apache2-foreground"]